services:
  db:
    image: postgres:latest
    container_name: postgres_fastapi
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    env_file:
      - .env

  app:
    build: .
    container_name: upwork_fastapi
    restart: always
    ports:
      - "8001:8001" 
    depends_on:
      - db
    networks:
      - backend
    env_file:
      - .env

volumes:
  postgres_data:

networks:
  backend:
